### PR TITLE
Custom Message Box

### PR DESCRIPTION
**Pull request by iiw2012**
Been trying to figure out swf the last few days, again. And I seem to have found a way to improve the endless text messages with device info.

First, a small picture with the results :)

MessageTextHTML_22

And how it was done.

I've enabled HTML markup for the MessageBox text. I've used a semi-standard component from a mod that adapts SkyUI for ultra-wide monitors as a base. I don't think this component is much different from the vanilla one.
Surprisingly, it was very easy to do, and I (probably) didn't break the game. Furthermore, the argument that enables this mode already exists, but cannot be used from Papyrus.

```as3
   function SetMessage(aText, abHTML)
   {
      this.Message.autoSize = "center";
      this.Message.setTextFormat(this.DefaultTextFormat);
      this.Message.setNewTextFormat(this.DefaultTextFormat);
      this.Message.html = true;                              // <-- changed to true
      if(this.Message.html)
      {
         this.Message.htmlText = aText;
      }
      else
      {
         this.Message.SetText(aText);
      }
      this.ResetDimensions();
      this.ProcessMessage(aText);
   }
```

And then you can use html and css that are supported by swf. Tags and styles subset is very limited, but with some imagination you can make something that looks like a table. Which is better perceived than the plain text. Not to mention color accents, font size etc.

In papyrus it is used like this.
```papyrus
loc_res += "<textformat tabstops='[30, 175, 225]' leading='-2'>"
loc_res += "<p align='left'>"
; ...
loc_res +="\t <Caption>: \t <Value>"
; ...
loc_res += "</p>"
loc_res += "</textformat>"
```

If this approach pays off, I see the following future improvements:
1. Switch to using a custom messagebox based component with html markup.
2. Switch from esp messages to papyrus. Then we can fill all message boxes with useful information. And the player won't have to dive into the depths of menus to, for example, find out the “vulnerabilities” of the device.

### CODE REVIEW

**Comment by IHateMyKite** [comment]
0rNB0S2

Tried it, and looks great. But will it not be better to find a way to enable the html only for messageboxes made by UD ? I think I can take a look in the skse on how to import the new menu. As currently, using this makes all other game messageboxes somehow distorted. I also dont know about compatibility with other HUD mods

**Comment by iiw2012** [comment]
> But will it not be better to find a way to enable the html only for messageboxes made by UD ?

So far I'm at the stage of: what if I change the existing menu. 
I'm not ready to make my own menu (or even a copy) yet, because I don't understand how exactly Papyrus interacts with swf. There must be native code involved?
Maybe it would be possible to implement custom native call to messagebox.swf, which would use the abHtml argument for the 'SetMessage' function I mentioned in the first post.

This option, if it is possible, will solve a lot of problems at once.

> As currently, using this makes all other game messageboxes somehow distorted. I also dont know about compatibility with other HUD mods

Yeah, that's one of the problems.

I used the swf adapted for ultra-wide resolution, so now all message boxes look compressed horizontally on normal monitors :)
And if we make our own copy for the message box, we'll have to make at least two versions for different aspects (it's not difficult, but it will complicate the installer).

As I said at the begining. It would be better to implement custom call to existing messagebox.swf with 'SetMessage' function using 'abHtml' argument. I'll see what I can do in this regard. Perhaps it could be done with Papyrus only, like in 'iWant Widgets'

**Comment by iiw2012** [comment]
I think I got it. Now we can optionally enable html markup in Debug.MessageBox. There are some issues with multi-page messages but it can be fixed.

Hypothetically, the list of buttons could be set in a similar way. So it is possible to make a full-fledged esp Message from the script. Just need to figure out how to catch button callback.

**Comment by iiw2012** [comment]
I tried to implement the idea with buttons, but failed to make reliable detection of the pressed button.

Maybe native calls will work better.

For the reference:

Papyrus function `Debug.MessageBox(...)` creates menu `MessageBoxMenu` with the instance name `MessageMenu`.

The original messagebox.swf ActionScript is here:

<details>
<summary>MessageBox</summary>

```as3
class MessageBox extends MovieClip
{
   var Message;
   var MessageText;
   var Divider;
   var MessageButtons;
   var ButtonContainer;
   var DefaultTextFormat;
   var Background_mc;
   static var WIDTH_MARGIN = 20;
   static var HEIGHT_MARGIN = 30;
   static var MESSAGE_TO_BUTTON_SPACER = 10;
   static var SELECTION_INDICATOR_WIDTH = 25;
   function MessageBox()
   {
      super();
      this.Message = this.MessageText;
      this.Divider = this.Divider;
      this.Message.noTranslate = true;
      this.MessageButtons = new Array();
      this.ButtonContainer = undefined;
      this.DefaultTextFormat = this.Message.getTextFormat();
      Key.addListener(this);
      gfx.io.GameDelegate.addCallBack("setMessageText",this,"SetMessage");
      gfx.io.GameDelegate.addCallBack("setButtons",this,"setupButtons");
   }
   function setupButtons()
   {
      if(undefined != this.ButtonContainer)
      {
         this.ButtonContainer.removeMovieClip();
         this.ButtonContainer = undefined;
      }
      this.MessageButtons.length = 0;
      var _loc8_ = arguments[0];
      if(arguments.length > 1)
      {
         this.ButtonContainer = this.createEmptyMovieClip("Buttons",this.getNextHighestDepth());
         var _loc7_ = 0;
         var _loc5_ = 1;
         while(_loc5_ < arguments.length)
         {
            if(arguments[_loc5_] != " ")
            {
               var _loc6_ = _loc5_ - 1;
               var _loc4_ = gfx.controls.Button(this.ButtonContainer.attachMovie("MessageBoxButton","Button" + _loc6_,this.ButtonContainer.getNextHighestDepth()));
               var _loc3_ = _loc4_.ButtonText;
               _loc3_.autoSize = "center";
               _loc3_.verticalAlign = "center";
               _loc3_.verticalAutoSize = "center";
               _loc3_.html = true;
               _loc3_.SetText(arguments[_loc5_],true);
               _loc4_.SelectionIndicatorHolder.SelectionIndicator._width = _loc3_._width + MessageBox.SELECTION_INDICATOR_WIDTH;
               _loc4_.SelectionIndicatorHolder.SelectionIndicator._y = _loc3_._y + _loc3_._height / 2;
               _loc4_._x = _loc7_ + _loc4_._width / 2;
               _loc7_ += _loc4_._width + MessageBox.SELECTION_INDICATOR_WIDTH;
               this.MessageButtons.push(_loc4_);
            }
            _loc5_ = _loc5_ + 1;
         }
         this.InitButtons();
         this.ResetDimensions();
         if(_loc8_)
         {
            Selection.setFocus(this.MessageButtons[0]);
         }
      }
   }
   function InitButtons()
   {
      var _loc2_ = 0;
      while(_loc2_ < this.MessageButtons.length)
      {
         this.MessageButtons[_loc2_].handlePress = function()
         {
         };
         this.MessageButtons[_loc2_].addEventListener("press",this.ClickCallback);
         this.MessageButtons[_loc2_].addEventListener("focusIn",this.FocusCallback);
         this.MessageButtons[_loc2_].ButtonText.noTranslate = true;
         _loc2_ = _loc2_ + 1;
      }
   }
   function SetMessage(aText, abHTML)
   {
      this.Message.autoSize = "center";
      this.Message.setTextFormat(this.DefaultTextFormat);
      this.Message.setNewTextFormat(this.DefaultTextFormat);
      this.Message.html = abHTML;
      if(abHTML)
      {
         this.Message.htmlText = aText;
      }
      else
      {
         this.Message.SetText(aText);
      }
      this.ResetDimensions();
   }
   function ResetDimensions()
   {
      this.PositionElements();
      var _loc3_ = this.getBounds(this._parent);
      var _loc2_ = Stage.height * 0.85 - _loc3_.yMax;
      if(0 > _loc2_)
      {
         this.Message.autoSize = false;
         var _loc4_ = _loc2_ * 100 / this._yscale;
         this.Message._height += _loc4_;
         this.PositionElements();
      }
   }
   function PositionElements()
   {
      var _loc4_ = this.Background_mc;
      var _loc3_ = 0;
      var _loc2_ = 0;
      while(_loc2_ < this.Message.numLines)
      {
         _loc3_ = Math.max(_loc3_,this.Message.getLineMetrics(_loc2_).width);
         _loc2_ = _loc2_ + 1;
      }
      var _loc6_ = 0;
      var _loc5_ = 0;
      if(this.ButtonContainer != undefined)
      {
         _loc6_ = this.ButtonContainer._width;
         _loc5_ = this.ButtonContainer._height;
      }
      _loc4_._width = Math.max(_loc3_ + 60,_loc6_ + MessageBox.WIDTH_MARGIN * 2);
      _loc4_._height = this.Message._height + _loc5_ + MessageBox.HEIGHT_MARGIN * 2 + MessageBox.MESSAGE_TO_BUTTON_SPACER;
      this.Message._y = (- _loc4_._height) / 2 + MessageBox.HEIGHT_MARGIN;
      this.ButtonContainer._y = _loc4_._height / 2 - MessageBox.HEIGHT_MARGIN - this.ButtonContainer._height / 2;
      this.ButtonContainer._x = (- this.ButtonContainer._width) / 2;
      this.Divider._width = _loc4_._width - MessageBox.WIDTH_MARGIN * 2;
      this.Divider._y = this.ButtonContainer._y - this.ButtonContainer._height / 2 - MessageBox.MESSAGE_TO_BUTTON_SPACER / 2;
   }
   function ClickCallback(aEvent)
   {
      gfx.io.GameDelegate.call("buttonPress",[Number(aEvent.target._name.substr(-1))]);
   }
   function FocusCallback(aEvent)
   {
      gfx.io.GameDelegate.call("PlaySound",["UIMenuFocus"]);
   }
   function onKeyDown()
   {
      if(Key.getCode() == 89 && this.MessageButtons[0].ButtonText.text == "Yes")
      {
         gfx.io.GameDelegate.call("buttonPress",[0]);
      }
      else if(Key.getCode() == 78 && this.MessageButtons[1].ButtonText.text == "No")
      {
         gfx.io.GameDelegate.call("buttonPress",[1]);
      }
      else if(Key.getCode() == 65 && this.MessageButtons[2].ButtonText.text == "Yes to All")
      {
         gfx.io.GameDelegate.call("buttonPress",[2]);
      }
   }
   function SetPlatform(aiPlatform, abPS3Switch)
   {
      if(aiPlatform != 0 && this.MessageButtons.length > 0)
      {
         Selection.setFocus(this.MessageButtons[0]);
      }
   }
}
```
</details>

The functions we are interested in are:
- `setupButtons()`, which takes arguments from the `arguments` array. The first argument is used for focus, and the remaining arguments contain the button enumeration.
- and `SetMessage(aText, abHTML)` with explicit arguments.

When the button is pressed, the callback 
```as3 
gfx.io.GameDelegate.call(“buttonPress”,[Number(aEvent.target._name.substr(-1))])
```
is called, in which an array with one element - the index of the pressed button - is passed.
So far, I haven't found a way to catch it in Papyrus. Some versions of messagebox.swf contain a `lastTabIndex` field, but it's not reliable. And I don't want to stick to a modded interface.

**Comment by IHateMyKite** [comment]
> I tried to implement the idea with buttons, but failed to make reliable detection of the pressed button.
> 
> Maybe native calls will work better.
> 
> For the reference:
> 
> Papyrus function `Debug.MessageBox(...)` creates menu `MessageBoxMenu` with the instance name `MessageMenu`.
> 
> The original messagebox.swf ActionScript is here:
> MessageBox
> 
> The functions we are interested in are:
> 
>     * `setupButtons()`, which takes arguments from the `arguments` array. The first argument is used for focus, and the remaining arguments contain the button enumeration.
> 
>     * and `SetMessage(aText, abHTML)` with explicit arguments.
> 
> 
> When the button is pressed, the callback
> 
> ```actionscript-3
> gfx.io.GameDelegate.call(“buttonPress”,[Number(aEvent.target._name.substr(-1))])
> ```
> 
> is called, in which an array with one element - the index of the pressed button - is passed. So far, I haven't found a way to catch it in Papyrus. Some versions of messagebox.swf contain a `lastTabIndex` field, but it's not reliable. And I don't want to stick to a modded interface.

There is already mod which does this, so I will just copy the implementation and add it to UD native plugin. You can then use new papyrus interfaces to add custom buttons

**Comment by iiw2012** [comment]
Tried another way to modify multibutton messages. (see UD_MenuMsgManager).

Now I handle the OnMenuOpen event and overwrite the text of the message and/or button. Since the message is processed by the  game itself, the output is always the correct identifier of the button pressed.

Actually, the overwritten message text will be enough to realize 95% of my ideas. Manually controlling the buttons will be very troublesome, as I'll have to overhaul the entire existing branching menu system. I'm not ready for that yet :)

So I will limit myself for now to message text using the described approach.

**Comment by IHateMyKite** [comment]
Incredible job. Tested it and looks very good. Only small issue I encountered is that sometimes the previous message box can be sen before it is replaced by the new one. Is that because of the event hijack you mentioned ? In that case the native approach I mentioned might solve this issue. But I will have to check how to inject the html format string in to it natively

**Comment by IHateMyKite** [comment]
I finally took a look at the native plugin, and added the functions for native handling of message boxes. It works basically same as your implementation, but there should be no longer issue with replacing the message box. Also, I didnt understand what the aafValues in ShowMessageBoxMenu, so these are currently not used. Looking up the function in project, it nowhere uses this argument, so it should be ok for now

**Comment by iiw2012** [comment]
> Only small issue I encountered is that sometimes the previous message box can be sen before it is replaced by the new one. Is that because of the event hijack you mentioned ?

This is strange because I implemented text overwriting in a very primitive way in OnMenuOpen. I don't interfere with the modal "window procedure" of the menu. And I have never had such an issue. 

Are you using any mods that modify the message box (over SkyUI)? Because I use "Widescreen fix" and they could fix something in there.

I left both variants: “Papyrus_UI” and “Native_UI” for comparison. Except for some visual differences, they work equally stable for me.

**Comment by iiw2012** [comment]
> Only small issue I encountered is that sometimes the previous message box can be sen before it is replaced by the new one. Is that because of the event hijack you mentioned ?

I didn't read carefully again :(

Yes. You can see the flickering of the text because of my way of injecting. It's the same window, it just changes its text and consequently its size.

**Comment by iiw2012** [comment]
All the changes that have been made:
- Added script `UD_MenuTextFormatter` for text formatting in 2 variants: Legacy and HTML. The last variant allows to use different visual tricks: line alignment, colored text, fonts, symbols.
- added script `UD_MenuMsgManager` for displaying menu windows in 3 variants: Legacy, Papyrus_UI and Native_UI (big thanks to @IHateMyKite). The last two variants allow you to display custom texts from the script in the menu window and change buttons (hopefully).
- All information windows and menus have been redesigned with the new features in mind. Except for some menus from DD.

The main goal was for the player to get all the information needed to select an action without having to go deep into the menu. I hope that I was able to fulfill this goal at least partially. If something can be improved or fixed, let's improve and fix it :)

**Review by kurotatsu77 — COMMENTED** [review]
This is beautiful and massive work! Idea of adding summary is great and improves QoL a lot. However right now one hint is missing on the said summary screen - which type of struggle is the best against the device. I'd suggest something like "It has MEDIUM resistance to magic which is lower than HIGH resistance to physical force." If resistance is 100% and more it's should be written as IMPOSSIBLE. maybe rephrased in such cases.

**Comment by iiw2012** [comment]
It's also worth mentioning my attempts to add help messages.

Help messages for basic functions have been added and implemented, but I have turned them off because they are unstable. They don't always work when the button name is replaced by an icon (e.g. [Strafe Left]). It looks ugly, so I've put that feature on hold for now.

**Comment by iiw2012** [comment]
Hopefully I've found and redone all menus visible to the player.

@IHateMyKite , please note the wordwrap setting that I turn off when displaying menus. If it works out, you can make it in the dll. It's not urgent at all since I've already implemented it as an injection in OnMenuOpen. 

```papyrus
UI.SetBool("MessageBoxMenu", "_root.MessageMenu" + ".MessageText.wordWrap", _InjectMessageWordWrap)     ; word wrap option
UI.Invoke("MessageBoxMenu", "_root.MessageMenu" + ".ResetDimensions")                                   ; recalculate window dimensions
```

In general, this setting has almost no effect on the text currently, but in the future it may save some particularly long line.

**Comment by IHateMyKite** [comment]
> Hopefully I've found and redone all menus visible to the player.
> 
> @IHateMyKite , please note the wordwrap setting that I turn off when displaying menus. If it works out, you can make it in the dll. It's not urgent at all since I've already implemented it as an injection in OnMenuOpen.
> 
> ```papyrus-skyrim
> UI.SetBool("MessageBoxMenu", "_root.MessageMenu" + ".MessageText.wordWrap", _InjectMessageWordWrap)     ; word wrap option
> UI.Invoke("MessageBoxMenu", "_root.MessageMenu" + ".ResetDimensions")                                   ; recalculate window dimensions
> ```
> 
> In general, this setting has almost no effect on the text currently, but in the future it may save some particularly long line.

Great. Thanks for your work. I think that there will be somewhere option for in in Native data too, but I will first need to have some example of how it looks before and after the wrap. There is no description for data, so I'm just finding the correct data by editing the data with Reclass to see how it affects the game. Thats how I found the switch for html which was not documented in clibs. 

I will give your latest commit spin, and if it works I will merge it. If there will be more things to do, new PR can be created

**Comment by IHateMyKite** [comment]
Found a way to do that after quite a long time of searching. In the end I didnt found any variable for the word wrap, except for the one in action script. For that reason I just made the native plugin to edit this variable just before the message box is shows. Because of that, there is no need to recalculate the size, and the message box will be opened already with word wrap disabled. Give it a test and let me know if it works. If it will work I will close the PR

**Comment by kurotatsu77** [comment]
Tried the latest PRNB from artifact - no messageboxes appear for me at all, missed dll changes?

**Comment by IHateMyKite** [comment]
> Tried the latest PRNB from artifact - no messageboxes appear for me at all, missed dll changes?

Strange. Can you check the papyrus log ? I think that there might be some issue with hooking the native functions to papyrus

**Comment by IHateMyKite** [comment]
> Tried the latest PRNB from artifact - no messageboxes appear for me at all, missed dll changes?

Strange. Can you check the papyrus log ? I think that there might be some issue with hooking the native functions to papyrus

> > > Tried the latest PRNB from artifact - no messageboxes appear for me at all, missed dll changes?
> > 
> > 
> > Strange. Can you check the papyrus log ? I think that there might be some issue with hooking the native functions to papyrus
> 
> In skse log "plugin UDNative.dll (00000001 UDNative 01000000) loaded correctly (handle 83)" UDNative,log not present despite having set logging to 2 in ini.

I meant the papyrus log. Im quite sure dll is ok. Issue is most likely that the native functions in papyrus script are named incorrectly. Its also possible that I forget to update dll on native repo. If you check papyrus log, you should see which functions are defined incorrectly, as it will write errors for them when the game starts

**Comment by kurotatsu77** [comment]
> > Tried the latest PRNB from artifact - no messageboxes appear for me at all, missed dll changes?
> 
> Strange. Can you check the papyrus log ? I think that there might be some issue with hooking the native functions to papyrus
> 
> > > > Tried the latest PRNB from artifact - no messageboxes appear for me at all, missed dll changes?
> > > 
> > > 
> > > Strange. Can you check the papyrus log ? I think that there might be some issue with hooking the native functions to papyrus
> > 
> > 
> > In skse log "plugin UDNative.dll (00000001 UDNative 01000000) loaded correctly (handle 83)" UDNative,log not present despite having set logging to 2 in ini.
> 
> I meant the papyrus log. Im quite sure dll is ok. Issue is most likely that the native functions in papyrus script are named incorrectly. Its also possible that I forget to update dll on native repo. If you check papyrus log, you should see which functions are defined incorrectly, as it will write errors for them when the game starts

[11/11/2024 - 06:21:15PM] error: Unbound native function "ShowArrayNonBlockingTemplate" called
[11/11/2024 - 06:21:15PM] Warning: Assigning None to a non-object variable named "::temp104"
stack:
	<unknown self>.ud_menumsgmanager._ShowMessageboxArrayTemplate() - "UD_MenuMsgManager.psc" Line 540
	[UD_MenuManager_Quest (FC00C320)].ud_menumsgmanager.ShowMessageBoxMenu() - "UD_MenuMsgManager.psc" Line ?
	[alias NPCSlot_Player on quest UD_NPCSlotsManager_Quest (4814E7EB)].ud_playerslotscript.fix() - "UD_CustomDevice_NPCSlot.psc" Line 465
	[UD_MCM (48112724)].ud_mcm_script.OptionSelectDebug() - "UD_MCM_script.psc" Line 2021
	[UD_MCM (48112724)].ud_mcm_script.OnOptionSelect() - "UD_MCM_script.psc" Line 1609
	[UD_MCM (48112724)].ud_mcm_script.SelectOption() - "SKI_ConfigBase.psc" Line 1177
	[SKI_ConfigManagerInstance (FE06E802)].SKI_ConfigManager.OnOptionSelect() - "SKI_ConfigManager.psc" Line 159

[11/11/2024 - 06:21:52PM] error: Unbound native function "ShowArrayNonBlockingTemplate" called
[11/11/2024 - 06:21:52PM] Warning: Assigning None to a non-object variable named "::temp104"
stack:
	<unknown self>.ud_menumsgmanager._ShowMessageboxArrayTemplate() - "UD_MenuMsgManager.psc" Line 540
	[UD_MenuManager_Quest (FC00C320)].ud_menumsgmanager.ShowMessageBoxMenu() - "UD_MenuMsgManager.psc" Line ?
	[Item 24 in container  (00000014)].UD_CustomHeavyBondage_RenderScript.DeviceMenu() - "UD_CustomDevice_RenderScript.psc" Line 2912
	[UD_UI_Quest (4815D067)].ud_userinputscript.OpenDeviceMenu() - "UD_UserInputScript.psc" Line 203
	[UD_UI_Quest (4815D067)].ud_userinputscript.OnKeyUp() - "UD_UserInputScript.psc" Line ?

**Comment by IHateMyKite** [comment]
Ok, so the issue was that I actually committed the changes to dll, but forget to push them. Because of that the NB used old files. Try it again after the NB finishes

**Comment by kurotatsu77** [comment]
> Ok, so the issue was that I actually committed the changes to dll, but forget to push them. Because of that the NB used old files. Try it again after the NB finishes

Yep, checked bunch of message boxes and they work as they should now.

**Comment by iiw2012** [comment]
Checked different combinations of render modes with redesigned menus, everything seems to work.

**Comment by IHateMyKite** [comment]
Thanks. Merging this PR in that case

**Pull request merged**
