### PR TITLE
updated the MCM script file and added MCM language files

### PR DESCRIPTION
**Pull request by YanJunSunYJS**
updated the MCM script file and added MCM language files

Fix typos, unify text

need new game or clean save to display text correctly!

### CODE REVIEW

**Comment by IHateMyKite** [comment]
Thank you for your contribution. Tested it works as intended. Only issue I found is that changing some string in translation file have no effect in game

- $General
- $NPCs Config
- $Other

My guess is that other mod is using the same string and so invalidate the changes made to the UD file. Might be better idea to name all string in same manner as it is done later with UD_ prefix

**Comment by YanJunSunYJS** [comment]
> Thank you for your contribution. Tested it works as intended. Only issue I found is that changing some string in translation file have no effect in game
> 
> * $General
> * $NPCs Config
> * $Other
> 
> My guess is that other mod is using the same string and so invalidate the changes made to the UD file. Might be better idea to name all string in same manner as it is done later with UD_ prefix

Tested on my end no problem.
If it can be explained, it means that other mods you installed contain these strings, and these corresponding strings have been localized, for example, we say $General here, if other mod also involve it, and translate it into other languages Text, then $General will definitely not be displayed as General, there is a sequence problem here. As long as the interface does not display $General

**Comment by IHateMyKite** [comment]
Found out some of the same string are in skyui_se_english.txt. I think that best solution would be to add prefix, so it will be impossible for the strings to get replaced by other translation file
[skyui_se_english.txt](https://github.com/IHateMyKite/UnforgivingDevices/files/11131749/skyui_se_english.txt)

**Comment by YanJunSunYJS** [comment]
> Found out some of the same string are in skyui_se_english.txt. I think that best solution would be to add prefix, so it will be impossible for the strings to get replaced by other translation file [skyui_se_english.txt](https://github.com/IHateMyKite/UnforgivingDevices/files/11131749/skyui_se_english.txt)

OK, i will change them :)

**Pull request closed without merging**
