### PR TITLE
Fixes and improvements in animations

### LINKED ISSUE #131: Something triggers horny animation without proper filtering
**Description**

Something triggers animations on the player without proper consideration for heavy bondage. That is, the player's hands are free, and the animation is played like actor wears yoke or armbinder.

According to the logs, some mod calls the **StartSoloAnimation** function for an animation that is not suitable for the current state of the player. The only place where such a call is possible is in here:
https://github.com/IHateMyKite/UnforgivingDevices/blob/50b4ca2ab5e75b93c774ad9a33565c161a33ec1f/Scripts/Source/zadlibs_UDPatch.psc#L751-L758

**To Reproduce**
1. Get into heavy bondage with a lot of vibrators.
2. (probably) Wait for the horny animation triggered by the unknown mod. Not sure if vibrator(s) should be turned on.
3. Remove heavy bondage.
4. Wait again for the horny animation triggered by the unknown mod.
5. This animation will look like the player is still in HB.

**Expected behavior**
Animations should correctly take into account the player's HB.

**Additional context**
Found on the latest version of 2023-03-12.
Checked with DD 5.2 beta 10 and DD 5.2.
<details>
  <summary>List of mods:</summary>

```
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
ccBGSSSE001-Fish.esm
ccQDRSSE001-SurvivalMode.esl
ccBGSSSE037-Curios.esl
ccBGSSSE025-AdvDSGS.esm
Unofficial Skyrim Special Edition Patch.esp
SexLab.esm
Devious Devices - Assets.esm
SexLabAroused.esm
Devious Devices - Integration.esm
Devious Devices - Expansion.esm
Devious Devices - Contraptions.esm
Schlongs of Skyrim - Core.esm
Expressive Facegen Morphs.esl
iWant Widgets.esl
ZaZAnimationPack.esm
SkyUI_SE.esp
UnforgivingDevices.esp
UnforgivingDevices - DD Patch.esp
Devious Devices SE patch.esp
Customizable Camera.esp
FNIS.esp
CBBE.esp
3BBB.esp
SOSPhysicsManager.esp
FemaleOutfitReplacer.esp
12FemaleBrows.esp
SLAnimLoader.esp
NibblesAnimObjects.esp
SLAL_AnimationsByLeito.esp
SLAL_AnimationByBakaFactory.esp
Schlongs of Skyrim.esp
SLALAnimObjBillyy.esp
FNISSexyMove.esp
RaceMenu.esp
XPMSE.esp
RaceMenuPlugin.esp
RaceMenuMorphsCBBE.esp
PR113_InterfaceWidgets.esp
KSHairdosSMP.esp
The Eyes Of Beauty - Elves Edition.esp
TheEyesOfBeauty.esp
UIExtensions.esp
widescreen_skyui_fix.esp
Alternate Start - Live Another Life.esp
```

</details>

### PR DESCRIPTION
**Pull request by iiw2012**
Updates and fixes in animation subsystem:
1. Added support for the solo animation sequences. It is now possible to use solo animations from SLAL packs. They will be ignored in **zadlibs_UDPatch** since functions from there need single animation events.
2. Added json files for solo animations from Billyy and Leito SLAL packs. They're used for horny and orgasm scenes.
3. Changed how GetActorConstraintsInt used. It's more explicit now. 
3.1. Fixed #131 
4. Fixes in json files.

### CODE REVIEW

**Comment by iiw2012** [comment]
I'll check the available SLAL packages, and if there are suitable solo animations, I'll add the json files here.

**Comment by IHateMyKite** [comment]
Do you intend to do some more features, or is the PR completed ? If its done, I will do a review and close it.

**Comment by iiw2012** [comment]
I'm not planning anything else, it's time to close.

**Review by IHateMyKite — APPROVED** [review]
Nice work!

**Pull request merged**
