### PR TITLE
Beta 6 fixes and changes

### PR DESCRIPTION
**Pull request by IHateMyKite**
This PR will be used to fix all reported issues with last beta 6

### CODE REVIEW

**Comment by Ethryan** [comment]
DD52+BRRF+ForHim DD Patch (**8 Errors**) got errors in latest NB:
DD52+ForHim also affected (**33 Errors**):

> [00:00] Checking for Errors in [FE 002] UnforgivingDevices - DD Patch.esp
[00:00] zad_gagHarnessBall "Gag (Harness) (Ball)" [ARMO:0400F561]
[00:00]     ARMO \ Armature \ MODL - Model FileName -> [FE001939] < Error: Could not be resolved >
[00:00] zad_cuffsLeatherCollar "Cuffs (Leather) (Collar)" [ARMO:0401BD28]
[00:00]     ARMO \ Armature \ MODL - Model FileName -> [FE0018BE] < Error: Could not be resolved >
[00:07] zadx_Collar_Posture_Red_Rendered [ARMO:07058465]
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE00007C] < Error: Could not be resolved >
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE00007D] < Error: Could not be resolved >
[00:07] zadx_Collar_Posture_White_Rendered [ARMO:07058467]
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE00007A] < Error: Could not be resolved >
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE00007B] < Error: Could not be resolved >
[00:07] zadx_Collar_Posture_Black_Rendered [ARMO:07058469]
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000078] < Error: Could not be resolved >
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000079] < Error: Could not be resolved >
[00:07] zadx_cuffs_Padded_Collar_Red_Rendered [ARMO:07058471]
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000074] < Error: Could not be resolved >
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000075] < Error: Could not be resolved >
[00:07] zadx_cuffs_Padded_Collar_White_Rendered [ARMO:07058473]
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000072] < Error: Could not be resolved >
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000073] < Error: Could not be resolved >
[00:07] zadx_cuffs_Padded_Collar_Black_Rendered [ARMO:07058475]
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000076] < Error: Could not be resolved >
[00:07]     ARMO \ Armature \ MODL - Model FileName -> [FE000077] < Error: Could not be resolved >

Affects both ESP and ESPFE.

I can try and fix them if you want.

**Comment by Ethryan** [comment]
BTW, can we delete the old [Merged Stale Branches](https://github.com/IHateMyKite/UnforgivingDevices/branches) of this repository?
They can easily be recreated if needed from the merge request in question.

**Comment by IHateMyKite** [comment]
> BTW, can we delete the old [Merged Stale Branches](https://github.com/IHateMyKite/UnforgivingDevices/branches) of this repository? They can easily be recreated if needed from the merge request in question.
> 
> 18 Branches is a lot.

Thanks for reminder. I have cleaned most of the merged branches.

**Comment by kurotatsu77** [comment]
One more small fix to include:
In the UD_PurifiedGoo_AME magic effect property UDRRM points to UD_Main, but this script was moved to UD_libs.
Need to correct this in the esp, because currently purified goo effect not working due to this error.

**Comment by kurotatsu77** [comment]
Here's another long-time standing really minor thing, which was unable to be added via merge, because it requires changing only case of one letter, see screenshot:
image

**Comment by kurotatsu77** [comment]
Also, from grammar standpoint, we need somehow replace all "ancle lock" to "ankle lock", but I don't know if there's nice and easy way to do it, both in UD esp and FOMOD patches and scripts.

**Comment by Ethryan** [comment]
You can filter for ancle and then go through and replace all instances of it.

**Comment by Ethryan** [comment]
Got a real nasty piece of thunderstorm here right now so my pc is unplugged, it’s going to pass in about a day. When it’s gone, i can error test this.

**Comment by IHateMyKite** [comment]
Sorry for additional changes, found some bugs while testing so I fixed it. Also finally implemented the possibility to select next lock after lockpick minigame ends, as I found out that it was not hard to implement.

**Review by kurotatsu77 — APPROVED** [review]
Looks good to me.
Please note that message edit has to be added manually into the main esp, as the merger ignores letter case changes.

**Comment by Ethryan** [comment]
I didn't find anything when testing either.

**Pull request merged**
