### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by YanJunSunYJS**

### CODE REVIEW

**Comment by YanJunSunYJS** [comment]
There was some typo involving the script global call, I didn't fix it :)

**Comment by IHateMyKite** [comment]
Thank you from contribution, but it seems like that the automated build didn't pass. Please check and fix all errors. From log it looks like that source of issue is from UD_ControlablePlug_RenderScript script

**Comment by YanJunSunYJS** [comment]
> Thank you from contribution, but it seems like that the [automated build](https://github.com/IHateMyKite/UnforgivingDevices/actions/runs/4625942532/jobs/8182171899) didn't pass. Please check and fix all errors. From log it looks like that source of issue is from UD_ControlablePlug_RenderScript script

Oh, yes. 
I wonder, are these variables related to esp plugin?
As I said before, I am afraid that after modifying the script, it will cause problems with the esp and cause the mod to not work properly

**Comment by IHateMyKite** [comment]
Yes renaming the property will cause issue, as the esp uses exact name. You would have to rename the property in esp so it links correctly. The script [UDCustomDeviceMain.psc](https://github.com/IHateMyKite/UnforgivingDevices/pull/140/files#diff-fab80d4955b523f2c33988be10387f8c7b883edab0b1e97ed4eea5af018febfc) is located on quest UD_CustomDevice_Quest. We are doing the changes to esp with patches, so you will have to place the changes to separate esp and push it to this PR. I will then merge it. See for example this pull request https://github.com/IHateMyKite/UnforgivingDevices/pull/106/files. The changes to esp are in file [PR106-UnforgivingDevices.esp](https://github.com/IHateMyKite/UnforgivingDevices/pull/106/files#diff-ae99fbd9a58921b7387fa20f44caf90aaf197465334d0b03e0388bbfb8f3d66c). Also don't forget to add the number of PR to the esp (so in this case PR140-GrammerFixes.esp for example)

**Comment by YanJunSunYJS** [comment]
> Yes renaming the property will cause issue, as the esp uses exact name. You would have to rename the property in esp so it links correctly. The script [UDCustomDeviceMain.psc](https://github.com/IHateMyKite/UnforgivingDevices/pull/140/files#diff-fab80d4955b523f2c33988be10387f8c7b883edab0b1e97ed4eea5af018febfc) is located on quest UD_CustomDevice_Quest. We are doing the changes to esp with patches, so you will have to place the changes to separate esp and push it to this PR. I will then merge it. See for example this pull request https://github.com/IHateMyKite/UnforgivingDevices/pull/106/files. The changes to esp are in file [PR106-UnforgivingDevices.esp](https://github.com/IHateMyKite/UnforgivingDevices/pull/106/files#diff-ae99fbd9a58921b7387fa20f44caf90aaf197465334d0b03e0388bbfb8f3d66c). Also don't forget to add the number of PR to the esp (so in this case PR140-GrammerFixes.esp for example)

:)

**Comment by IHateMyKite** [comment]
In that case I will do the esp patch, its only small fix. I recommend you to use xEdit for such small changes, as CK is not best tool for editing esps. It's great for creating locations, dungeons, etc., but it's a pain  if you are supposed to do anything script related.

**Comment by IHateMyKite** [comment]
Small walkthrough so you might get better idea what I mean. It takes some time but once you understand some basics about esp format, it will be easy to use any tool to do the work
pic
pic
pic
pic
pic
pic

**Comment by IHateMyKite** [comment]
There is obviously still an issue with the UD_ControllablePlugs_RenderScript. Issue is that the script is calling old named properties which dont exist anymore
pic
Once you fix it, I will merge it.

**Pull request closed without merging**
