### PR TITLE
Prototype: Reworked init of many modules

### PR DESCRIPTION
**Pull request by IHateMyKite**
Prototype for testing fixes of mod initialization issues

### CODE REVIEW

**Comment by Ethryan** [comment]
Ran into theese when testing: 

Error: Cannot call UDReady() on a None object, aborting function call
stack:
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.CONFIG_ABC() - "zadBoundCombatScript_UDPatch.psc" Line 117
[04/12/2023 - 09:00:24PM] WARNING: Assigning None to a non-object variable named "::temp19"
stack:
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.CONFIG_ABC() - "zadBoundCombatScript_UDPatch.psc" Line 117
[04/12/2023 - 09:00:39PM] Error: Cannot call UDReady() on a None object, aborting function call
stack:
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.CONFIG_ABC() - "zadBoundCombatScript_UDPatch.psc" Line 117
[04/12/2023 - 09:00:39PM] WARNING: Assigning None to a non-object variable named "::temp19"
stack:
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.CONFIG_ABC() - "zadBoundCombatScript_UDPatch.psc" Line 117
[04/12/2023 - 09:00:39PM] Error: Cannot call UDReady() on a None object, aborting function call
stack:
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.Maintenance_ABC() - "zadBoundCombatScript_UDPatch.psc" Line 105
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.OnUpdate() - "zadBoundCombatScript_UDPatch.psc" Line 20
[04/12/2023 - 09:00:39PM] WARNING: Assigning None to a non-object variable named "::temp15"
stack:
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.Maintenance_ABC() - "zadBoundCombatScript_UDPatch.psc" Line 105
	[zadQuest (1500F624)].zadBoundCombatScript_UDPatch.OnUpdate() - "zadBoundCombatScript_UDPatch.psc" Line 20

Running Zaz 8.

**Comment by Ethryan** [comment]
[Save2_8545F9F1_0_507269736F6E6572_AbandonedPrison01_000004_20230412190356_1_1.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11215021/Save2_8545F9F1_0_507269736F6E6572_AbandonedPrison01_000004_20230412190356_1_1.zip)
The save.

**Comment by IHateMyKite** [comment]
Do you have PR144_InitProto.esp enabled ?

**Comment by Ethryan** [comment]
Yes

**Comment by Ethryan** [comment]
[Papyrus.0.log](https://github.com/IHateMyKite/UnforgivingDevices/files/11215098/Papyrus.0.log)
Pap log from latest test.

**Comment by Ethryan** [comment]
[Papyrus.0.log](https://github.com/IHateMyKite/UnforgivingDevices/files/11215182/Papyrus.0.log)
[Save2_C1790176_0_507269736F6E6572_AbandonedPrison01_000000_20230412193519_1_1.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11215194/Save2_C1790176_0_507269736F6E6572_AbandonedPrison01_000000_20230412193519_1_1.zip)
Files to check so no other errors appear, the new NB works.

**Comment by IHateMyKite** [comment]
Looks promising. Not even suspended script remained.
pic
Did you check both with and without DCL ?

**Comment by Ethryan** [comment]
Only without, i'm going to activate DCL and test now.

**Comment by Ethryan** [comment]
The only thing in the log i found was 
image

**Comment by IHateMyKite** [comment]
Caused by some patch. What DD patch have you installed ?

**Comment by Ethryan** [comment]
Security Overhaul and DD Patch, and a version of my Piercing Patch i am working on.

**Comment by Ethryan** [comment]
image
Found it!

**Comment by IHateMyKite** [comment]
Yes, I already got through all patches and only 5.2 patches have the quest. All off them still reference the property so I will update it and merge it

**Comment by IHateMyKite** [comment]
In that case I will let someone else do the review and merge it. Hopefully will help some users which were having issue with starting UD

**Comment by Ethryan** [comment]
Will the pr144 be merged into the main esp too?

**Comment by IHateMyKite** [comment]
Yes. I will also remove some additional no longer used forms like form lists for UDRRM

**Comment by Ethryan** [comment]
[save passed.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11233170/save.passed.zip)
[save.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11233171/save.zip)

Uh oh, a problem...

It randomly stops working, and randomly passes. between the 2 saves 1 passed, the other one didn't and the only thing i dids was try to start the game. no esp changes at all.

**Comment by IHateMyKite** [comment]
Welp, I will try to do some additional optimization then

**Comment by IHateMyKite** [comment]
I did some changes to how MCM is actually initiated. Try if it help

**Comment by IHateMyKite** [comment]
Did some more changes after checking the save. Also, try [this ](https://www.nexusmods.com/skyrimspecialedition/mods/77779) mod, as it will force papyrus to dump more info to papyrus log. So it should show more informations about the suspended stacks. Note that you hav to toggle this feature on in ini file

**Comment by Ethryan** [comment]
PapyrusTweaks are already running in my LO, and from what i noticed, it might have something to do with the first autoSave interupting the scripts, and then they not starting up again after the save is done. But this is just a guess.

**Comment by IHateMyKite** [comment]
That should be not the case if you have default setting. Did the last changes helped in any way ?

**Comment by Ethryan** [comment]
I havn't run into it again, but i tested it a lot yesterday and didn't get it. Sadly it seems hard to troubleshoot.

**Comment by IHateMyKite** [comment]
Its possible that you have to exit and start a game for it to happen. Someone reported that if they get the MCM issue, all it takes is to go to main menu and start new game again.

**Review by kurotatsu77 — APPROVED** [review]
So far didn't managed to get any bugs to appear, looks good to me. Tested on LE.

**Pull request merged**
