### PR TITLE
Fixes and improvements

### LINKED ISSUE #198: SwapDevices
**Describe the bug**
SwapDevices functions seem to not working right.

**To Reproduce**
Used code
libs.SwapDevices(akTarget, UDlibs.AbadonPlug, libs.zad_deviousPlugVaginal) 
wrapped in check for device present, but it failed to remove device already worn and equip new device.

**Expected behavior**
Replace the devices.

**Desktop (please complete the following information):**
Tested last on DD NG 0.3.6 and UD NB.

### LINKED ISSUE #199: Plug inflation events
**Describe the bug**
Inflatable plugs (both UD and framework patched ones) seem not to have receiving events from framework, like "You accidentally bumped your pump and inflated your plug" etc. Own UD inflation events are working as they should.

**Desktop (please complete the following information):**
Tested last on DD NG 0.3.6 and UD NB.

### PR DESCRIPTION
**Pull request by IHateMyKite**
- Fixes #199 
- Fixes #198 

Requires new DD API from commit https://github.com/ponzipyramid/DeviousDevicesNG/commit/1d622bcf57acbb7d081ecaa65ccbe28a72634294

### CODE REVIEW

**Comment by IHateMyKite** [comment]
@kurotatsu77 Let me know if the last commit fixes the #202 . It requires the latest dll from DDNG repo. Here it is for simplicity
[DeviousDevices.zip](https://github.com/user-attachments/files/16645587/DeviousDevices.zip)

**Comment by kurotatsu77** [comment]
> @kurotatsu77 Let me know if the last commit fixes the #202 . It requires the latest dll from DDNG repo. Here it is for simplicity [DeviousDevices.zip](https://github.com/user-attachments/files/16645587/DeviousDevices.zip)

Ran this PRNB and DLL you supplied - yep, both issues are fixed now. 
All inflation events fire off properly.
Also tested SwapDevices  function - worked as expected this time.

While testing spotted weird bug - after player control disabled and enabled again sometimes part of control still stays disabled, like mingame is running. This disabled state persists even through game being loaded and even through exit to main menu and load game! Running UD fixes not re-enables controls. But running any UD minigame restores controls properly. Issue can be spotted by running DIN free use feature or some other scenes which disable player controls. It's not 100%, seems a bit random. And I'm quite sure I never saw it before I've used dll from here. Something to investigate?

**Comment by IHateMyKite** [comment]
> > @kurotatsu77 Let me know if the last commit fixes the #202 . It requires the latest dll from DDNG repo. Here it is for simplicity [DeviousDevices.zip](https://github.com/user-attachments/files/16645587/DeviousDevices.zip)
> 
> Ran this PRNB and DLL you supplied - yep, both issues are fixed now. All inflation events fire off properly. Also tested SwapDevices function - worked as expected this time.
> 
> While testing spotted weird bug - after player control disabled and enabled again sometimes part of control still stays disabled, like mingame is running. This disabled state persists even through game being loaded and even through exit to main menu and load game! Running UD fixes not re-enables controls. But running any UD minigame restores controls properly. Issue can be spotted by running DIN free use feature or some other scenes which disable player controls. It's not 100%, seems a bit random. And I'm quite sure I never saw it before I've used dll from here. Something to investigate?

Can you share the UD_Native.log with maximum logging when this issue happens ? Also, can this be replicated ?

**Comment by kurotatsu77** [comment]
> Can you share the UD_Native.log with maximum logging when this issue happens ? Also, can this be replicated ?

Tried hard to replicate this issue and didn't managed to do so... Probably can be written off as weird script lag I guess...

**Comment by IHateMyKite** [comment]
> > Can you share the UD_Native.log with maximum logging when this issue happens ? Also, can this be replicated ?
> 
> Tried hard to replicate this issue and didn't managed to do so... Probably can be written off as weird script lag I guess...

In that case, I think this is ready to be merged. This PR should fix all 3 latest problems. Can you do a quick review ?

**Review by kurotatsu77 — APPROVED** [review]
Great work, it really helped!

**Pull request merged**
